image: rustlang/rust:nightly

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

test:cargo:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - time cargo test --verbose --jobs 1 --release # Don't parallelize ize to make errors more readable
  cache:
    paths:
    - target/
    - cargo/
