[package]
name = "sparkpost"
version = "0.0.3"
authors = ["mygnu <tech@hgill.io>"]
keywords = ["email", "sparkpost","reqwest"]
description = "Rust bindings for sparkpost email api v1"
documentation = "https://docs.rs/crate/sparkpost"
repository = "https://gitlab.com/mygnu/spark_post"
readme="README.md"
license="LGPL-3.0+"
categories = ["api-bindings"]


[dependencies]
reqwest="^0.9.1"
serde_json="^1.0"
serde_derive = "^1.0"
serde = "^1.0"

[dev-dependencies]
lazy_static = "^1.1.0"
dotenv = "^0.13.0"
pretty_assertions = "^0.5.1"

[badges]
#gitlab = {repository = "https://gitlab.com/mygnu/spark_post"}
maintenance = { status = "experimental" }
