[package]
name = "spark_post"
version = "0.0.0"
authors = ["mygnu <tech@hgill.io>"]
edition = "2018"

[dependencies]

reqwest="^0.9.1"
serde_json="^1.0.28"
serde_derive = "^1.0.79"
serde = "^1.0.79"

[dev-dependencies]
lazy_static = "^1.1.0"
dotenv = "^0.13.0"
pretty_assertions = "^0.5.1"
