[package]
name = "sparkpost"
version = "0.5.0"
authors = ["mygnu <tech@hgill.io>"]
keywords = ["email", "sparkpost","reqwest"]
description = "Rust bindings for sparkpost email api v1"
documentation = "https://docs.rs/crate/sparkpost"
repository = "https://gitlab.com/mygnu/spark_post"
readme="README.md"
license="MPL-2.0+/LGPL-3.0+"
categories = ["api-bindings","web-programming"]


[dependencies]
reqwest="0.9"
serde_json="1.0"
serde_derive = "1.0"
serde = "1.0"
chrono = {version = "0.4", features = ["serde"]}

[dev-dependencies]
base64 = "0.10"
lazy_static = "1.2"
dotenv = "0.13"
pretty_assertions = "0.5"

[badges]
#gitlab = {repository = "https://gitlab.com/mygnu/spark_post"}
maintenance = { status = "actively-developed" }

[profile.release]
lto = true
opt-level = 3
